### ISSUE TITLE
Classrooms für GitHub

### ISSUE THREAD

**Issue by iwilfried** [suchja/github-fuer-entwickler#10]

**Comment by suchja** [comment]
Hallo Wilfried,

das klingt erstmal sehr spannend. Allerdings ist mir noch nicht ganz klar wie das genau funktionieren soll. Vielleicht kannst du deine Idee noch etwas mehr im Detail beschreiben.
- Für wen soll der "Classroom for GitHub" sein (du und ein paar von dir ausgesuchte Personen oder jeder)?
- Was für einen Kurs willst du entwickeln?
- Welche Funktionen braucht deine Gruppe um den Kurs zu entwickeln und wie sind die wichtigsten Arbeitsabläufe?

Die verlinkte Seite spricht von Jekyll, Markdown und GitHub. Das ist eine gute Kombination und kann so auch eingesetzt werden um eine Webseite (unabhängig von GitHub Pages) zu erstellen. Mein Blog (www.lernmoment.de) ist beispielsweise damit umgesetzt.

Wenn du konkrete Fragen hast, dann immer man her damit ;-).

Jan

**Comment by iwilfried** [comment]
Hallo Jan,

Ich möchte erstmal nur ausgesuchte Pesonen im Classroom haben.  Der Kurs soll sich mit Ionic2 /Typescript/Angular2 Framework befassen. Hier aber in erster Linie mit Apps zum Thema MicroLearning

Ich gebe das Outline und Inhalte vor und die Partner sollen verbessern , erweitern  und  creative Ideen einbringen. Die entsprechenden Contributions werden dann von einem kleinen Team verabschiedet und in den Master eingefügt.

Das ist die erste Idee, wer weiss, was am Ende draus wird.

Die Organisation heisst : YouCan-Trust / DreamWork auf dem GitHub.

Ich bin gespannt, wie weit ich komme

Wilfried

**Comment by suchja** [comment]
Wie weit bist du denn mit deinem "Jekyll.Problem" gekommen? Wenn du da noch Fragen hast, dann kannst du dich gerne melden.

**Comment by iwilfried** [comment]
ich habe das Problem gelöst mit Hilfe dieser Webseite http://jmcglone.com/
guides/github-pages/
und hier ist das Ergebnis: https://youcan-trust.github.io/

ich überlege jetzt noch eine Strategie, wie man einen Kurs mit mehreren
Personen  auf GitHub aufsetzen kann. Jede Lektion einen Folder in einem
Repo oder für jede Lektion ein Repo. Für jede Repo eine GitHub page
(Jekyll) und den Beispiel code ins Repo. Gar nicht so einfach.
Was wäre die beste Möglichkeit. Eine Idee ?

**Comment by suchja** [comment]
@iwilfried 
Ich denke, dass es Sinn macht den kompletten Kurs in einem Repository zu haben.
Du kannst ja einfach für jede Lektion einen eigenen Ordner anlegen in dem es ein
README.md gibt welches die Lektion beschreibt und dann entsprechenden Quellcode.

Ich mache es sonst so, dass ich separate Repositories für komplette Beispielprojekte mache.

Wenn du alles in einem Repository machst, hast du den Vorteil, dass du Funktionalitäten
wie Issues und das neue Projekt an einem zentralen Platz hast. Wenn du mit mehreren
Repositories arbeitest, dann fragt man sich immer wo nun genau ein Issue eröffnet werden
sollte.
